import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";


export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" rel="stylesheet" />
      </head>
      <body>
        <Navbar/>
        <main className="container mx-auto px-5 pt-10">
        {children}
        </main>
      </body>
    </html>
  );
}
